### PR TITLE
Ignore draft PRs

### PR DESCRIPTION
**Pull request by aornugent**
We can test that:

- [x] this doesn't run while in draft
- [x] does run when ready for review
- [x] doesn't run when switched back to draft

Follows: https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/16

### CODE REVIEW

**Comment by aornugent** [comment]
So far so good. Switching to non-draft.

image

**Comment by aornugent** [comment]
Runs fine when ready for review. Last check will be a to see if switching back to draft overrides checks.

image

**Comment by aornugent** [comment]
All checks now suppressed on draft PRs. This is ready for merge.

image

**Comment by dfalster** [comment]
Awesome!

**Review by dfalster — APPROVED** [review]
Looks great, if this excludes draft PRs then that's great!

**Pull request merged**
