### PR TITLE
Proposed fix to issue with integration of density

### PR DESCRIPTION
**Pull request by Becca-90**
Issue #344

### CODE REVIEW

**Comment by aornugent** [comment]
Thanks @Becca-90!

You can see above that your PR failed the automated tests - which isn't a problem because it tells you what to fix! Clicking through one of the `R-CMD-check` actions above and scrolling all the way to the bottom takes me to [this error message](https://github.com/traitecoevo/plant/runs/7539336119?check_suite_focus=true#step:9:289).

The fix is simple: you need to add the `dplyr::` namespace to `rename`.

You can run these tests locally, before pushing your changes with `devtools::test()` or the keyboard shortcut `Ctrl + Shift + T`.

I wasn't able to tell from just reading your code how these changes fixed the issue. Could you please describe your solution?

**Comment by Becca-90** [comment]
Morning!

So the issue was in the last part of the integrate_across_size_distribution function. We previously had individuals calculate like this:

```{r}
    dplyr::summarise(
      individuals = -trapezium(.data$height, .data$density),
      min_height = min(.data$height),
      dplyr::across(where(is.double), ~ -trapezium(height, density*.x)),
      .groups="drop"
    )
```
it was basically causing the trapezium integration to be done twice for individuals and giving some crazy output... so in the second call of trapezium (below) we just had to isolate everything that isn't already integrated to integrate across... I think that's essentially what was going on!
We also renamed individuals as density integrated (a bit clearer?)

```{r}
    dplyr::summarise(
      density_integrated = -plant:::trapezium(.data$height, .data$density), 
      min_height = min(.data$height),
      dplyr::across(where(is.double) & !c(density, density_integrated, min_height) , ~-plant:::trapezium(height, density * .x)), 
        .groups = "drop") %>% 
    rename(density = density_integrated)
```

**Review by aornugent — APPROVED** [review]

**Comment by aornugent** [comment]
@dfalster - I'm happy to merge this without a dedicated test, which can be submitted in a second PR. Thoughts?

**Comment by dfalster** [comment]
I'll add a test tomorrow. The template code is already there

**Pull request merged**
