### PR TITLE
Scaffolder

### PR DESCRIPTION
**Pull request by johnWilshire**
Implementation of a scaffolder that will enable new strategies to be created quickly from existing strategies, see #183 for more details.

### CODE REVIEW

**Comment by dfalster** [comment]
Hi @johnWilshire 
This is really nice. I'm thinking of modifying to run from the root directory. Any objections?

**Comment by johnWilshire** [comment]
None, I think that makes sense.

**Review by dfalster — COMMENTED** [review]
Hi John, Nice work with the scaffolder. I really like

- the approach for autogenerating code
- use of feature branch & code review
- thorough coverage of all the files needing modification
- adding details to the developer notes
- it works!

I  just pushed some modifications, including 

- Convert scaffolder to fully R based workflow
- change to run from project root
- introduce a few template functions to remove repeated code
- Enhance description of strategies and scaffolder in developer notes

Can you verify that my changes work for you too? Then I'll merge the branch

**Comment by johnWilshire** [comment]
Thanks your changes make work and clean up the scaffolding code, merging now.

**Pull request merged**
