### PR TITLE
Update vignettes

### PR DESCRIPTION
**Pull request by aornugent**
Aiming to work through all example vignettes to ensure they continue to work with new function names.

- [x] Individuals
- [x] Patches
- [x] Equilibrium
- [x] Emergent
- [x] Fitness
- [x] Cohort spacing
- [ ] Parameters

Appreciate all feedback on writing style, clarity and correctness, particularly regarding PlantPlus, LCP and #206.

### CODE REVIEW

**Comment by aornugent** [comment]
Also rejigged installation instructions but happy to move to different PR as needed.

**Comment by aornugent** [comment]
I've added `Getting Started` and `Implementing a new strategy` to remake and pkgdown, but havent  tried rebuilding the website. Please verify these show up in the right place.

**Comment by aornugent** [comment]
Closes #204 and #245

**Review by dfalster — APPROVED** [review]
Great work on updating these Andrew!!

**Pull request merged**
